<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cubit.Core\Cubit.Core.csproj" />
    <ProjectReference Include="..\Cubit.Mcp\Cubit.Mcp.csproj" />
    <ProjectReference Include="..\Cubit.Animation\Cubit.Animation.csproj" />
  </ItemGroup>
</Project>
