<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cubit.Audio\Cubit.Audio.csproj" />
    <PackageReference Include="Silk.NET.SDL" Version="2.23.0" />
  </ItemGroup>
</Project>
